#version: '5'
#services:
#  mysql:
#    image: mysql:latest
#    ports:
#      - "3307:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: mistret123
#      MYSQL_DATABASE: rentalapp
#    command: mysqld --sql_mode=""
#    volumes:
#      - ./my.cnf:/etc/mysql/my.cnf
#    container_name: mysqlimage1
#
#  app:
#    image: crudimage:crudapp
#    ports:
#      - "8090:8080"
#    environment:
#      SPRING_JPA_GENERATE_DDL: true
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
#      SPRING_JPA_SHOW_SQL: true
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rentalapp
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: mistret123
#      SERVER_ERROR_INCLUDE_MESSAGE: always
#    depends_on:
#      - mysql
#    container_name: crudappimage1